const BRAINTREE_MERCHANT_ID = 'czbcdgpmfz25rt4w'
const BRAINTREE_PUBLIC_KEY = 'g8gz7stxpyzkf359'
const BRAINTREE_PRIVATE_KEY = '2a431d078d4bf7719307bb08eb75f3e8'
const BRAINTREE_ENVIRONMENT = 'sandbox'


module.exports = {
	BRAINTREE_MERCHANT_ID:BRAINTREE_MERCHANT_ID,
	BRAINTREE_PUBLIC_KEY:BRAINTREE_PUBLIC_KEY,
	BRAINTREE_PRIVATE_KEY:BRAINTREE_PRIVATE_KEY,
	BRAINTREE_ENVIRONMENT:BRAINTREE_ENVIRONMENT
}